## Numpy

In [1]:
import numpy as np

### Creating Arrays

#### np.array(list)

In [8]:
a = np.array([1, 2, 3])
b = np.array([(1.5, 2, 3), (4, 5, 6)], dtype = float)
c = np.array([[(1.5, 2, 3), (4, 5, 6)], [(3, 2, 1), (4, 5, 6)]], dtype = float)

In [12]:
a

array([1, 2, 3])

In [13]:
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [14]:
c

array([[[1.5, 2. , 3. ],
        [4. , 5. , 6. ]],

       [[3. , 2. , 1. ],
        [4. , 5. , 6. ]]])

#### np.zeros(shape)

In [7]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

#### np.ones(shape)

In [8]:
np.ones((2, 3, 4), dtype = np.int16)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

#### np.arange(start, end, step)

In [9]:
d = np.arange(10, 25, 5) # end값은 포함하지 않음
d

array([10, 15, 20])

#### np.linspace(start, end, count)

In [11]:
np.linspace(0, 2, 9) # end값 포함

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

#### np.full(shape, fill_value)

In [10]:
e = np.full((2, 2), 7)
e

array([[7, 7],
       [7, 7]])

#### np.eye(n) => nxn identity matrix 

In [4]:
f = np.eye(2)
f

array([[1., 0.],
       [0., 1.]])

#### np.random.random(shape)

In [5]:
np.random.random((2, 2))

array([[0.01576658, 0.9711831 ],
       [0.20428686, 0.55660421]])

#### np.empty(shape)

In [7]:
np.empty((3, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

### Array Mathematics

#### Arithmetics Operations

In [11]:
g = a - b
g

array([[-0.5,  0. ,  0. ],
       [-3. , -3. , -3. ]])

In [12]:
np.subtract(a, b)

array([[-0.5,  0. ,  0. ],
       [-3. , -3. , -3. ]])

In [13]:
b + a

array([[2.5, 4. , 6. ],
       [5. , 7. , 9. ]])

In [14]:
np.add(b, a)

array([[2.5, 4. , 6. ],
       [5. , 7. , 9. ]])

In [16]:
a / b

array([[0.66666667, 1.        , 1.        ],
       [0.25      , 0.4       , 0.5       ]])

In [17]:
np.divide(a, b)

array([[0.66666667, 1.        , 1.        ],
       [0.25      , 0.4       , 0.5       ]])

In [18]:
a * b

array([[ 1.5,  4. ,  9. ],
       [ 4. , 10. , 18. ]])

In [19]:
np.multiply(a, b)

array([[ 1.5,  4. ,  9. ],
       [ 4. , 10. , 18. ]])

In [20]:
np.exp(b)

array([[  4.48168907,   7.3890561 ,  20.08553692],
       [ 54.59815003, 148.4131591 , 403.42879349]])

In [21]:
np.sqrt(b)

array([[1.22474487, 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [22]:
np.sin(a)

array([0.84147098, 0.90929743, 0.14112001])

In [23]:
np.cos(b)

array([[ 0.0707372 , -0.41614684, -0.9899925 ],
       [-0.65364362,  0.28366219,  0.96017029]])

In [25]:
np.log(a)

array([0.        , 0.69314718, 1.09861229])

In [26]:
e.dot(f)

array([[7., 7.],
       [7., 7.]])

### Comparison

In [28]:
a == b

array([[False,  True,  True],
       [False, False, False]])

In [29]:
a < 2

array([ True, False, False])

In [30]:
np.array_equal(a, b)

False